ERROR - 2023-04-22 02:56:47 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\proyectoFundamentos\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\proyectoFundamentos\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'usuarios', 3306, '', 0)
#1 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\proyectoFundamentos\app\Models\Usuario.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\proyectoFundamentos\app\Controllers\Home.php(24): App\Models\Usuario->obtenerUsuario(Array)
#6 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(934): App\Controllers\Home->login()
#7 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\proyectoFundamentos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\proyectoFundamentos\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\proyectoFundamentos\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\proyectoFundamentos\app\Models\Usuario.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\proyectoFundamentos\app\Controllers\Home.php(24): App\Models\Usuario->obtenerUsuario(Array)
#5 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(934): App\Controllers\Home->login()
#6 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\proyectoFundamentos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\proyectoFundamentos\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-04-22 02:56:47 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `personas`
WHERE `usuario` = :usuario:', [...], false)
 3 APPPATH\Models\Usuario.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(24): App\Models\Usuario->obtenerUsuario([...])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->login()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\proyectoFundamentos\\public\\index.php')
ERROR - 2023-04-22 02:57:07 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\proyectoFundamentos\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\proyectoFundamentos\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'usuarios', 3306, '', 0)
#1 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\proyectoFundamentos\app\Models\Usuario.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\proyectoFundamentos\app\Controllers\Home.php(24): App\Models\Usuario->obtenerUsuario(Array)
#6 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(934): App\Controllers\Home->login()
#7 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\proyectoFundamentos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\proyectoFundamentos\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\proyectoFundamentos\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\proyectoFundamentos\app\Models\Usuario.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\proyectoFundamentos\app\Controllers\Home.php(24): App\Models\Usuario->obtenerUsuario(Array)
#5 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(934): App\Controllers\Home->login()
#6 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\proyectoFundamentos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\proyectoFundamentos\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-04-22 02:57:07 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `personas`
WHERE `usuario` = :usuario:', [...], false)
 3 APPPATH\Models\Usuario.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(24): App\Models\Usuario->obtenerUsuario([...])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->login()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\proyectoFundamentos\\public\\index.php')
ERROR - 2023-04-22 02:57:17 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\proyectoFundamentos\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\proyectoFundamentos\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'usuarios', 3306, '', 0)
#1 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\proyectoFundamentos\app\Models\Usuario.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\proyectoFundamentos\app\Controllers\Home.php(24): App\Models\Usuario->obtenerUsuario(Array)
#6 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(934): App\Controllers\Home->login()
#7 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\proyectoFundamentos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\proyectoFundamentos\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\proyectoFundamentos\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\proyectoFundamentos\app\Models\Usuario.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\proyectoFundamentos\app\Controllers\Home.php(24): App\Models\Usuario->obtenerUsuario(Array)
#5 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(934): App\Controllers\Home->login()
#6 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\proyectoFundamentos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\proyectoFundamentos\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-04-22 02:57:17 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `personas`
WHERE `usuario` = :usuario:', [...], false)
 3 APPPATH\Models\Usuario.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(24): App\Models\Usuario->obtenerUsuario([...])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->login()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\proyectoFundamentos\\public\\index.php')
ERROR - 2023-04-22 02:57:26 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\proyectoFundamentos\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\proyectoFundamentos\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'usuarios', 3306, '', 0)
#1 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\proyectoFundamentos\app\Models\Usuario.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\proyectoFundamentos\app\Controllers\Home.php(24): App\Models\Usuario->obtenerUsuario(Array)
#6 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(934): App\Controllers\Home->login()
#7 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\proyectoFundamentos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\proyectoFundamentos\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\proyectoFundamentos\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\proyectoFundamentos\app\Models\Usuario.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\proyectoFundamentos\app\Controllers\Home.php(24): App\Models\Usuario->obtenerUsuario(Array)
#5 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(934): App\Controllers\Home->login()
#6 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\proyectoFundamentos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\proyectoFundamentos\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-04-22 02:57:26 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `personas`
WHERE `usuario` = :usuario:', [...], false)
 3 APPPATH\Models\Usuario.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(24): App\Models\Usuario->obtenerUsuario([...])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->login()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\proyectoFundamentos\\public\\index.php')
ERROR - 2023-04-22 02:57:52 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\proyectoFundamentos\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\proyectoFundamentos\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'usuarios', 3306, '', 0)
#1 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\proyectoFundamentos\app\Models\Usuario.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\proyectoFundamentos\app\Controllers\Home.php(24): App\Models\Usuario->obtenerUsuario(Array)
#6 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(934): App\Controllers\Home->login()
#7 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\proyectoFundamentos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\proyectoFundamentos\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\proyectoFundamentos\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\proyectoFundamentos\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\proyectoFundamentos\app\Models\Usuario.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\proyectoFundamentos\app\Controllers\Home.php(24): App\Models\Usuario->obtenerUsuario(Array)
#5 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(934): App\Controllers\Home->login()
#6 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\proyectoFundamentos\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\proyectoFundamentos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\proyectoFundamentos\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-04-22 02:57:52 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `personas`
WHERE `usuario` = :usuario:', [...], false)
 3 APPPATH\Models\Usuario.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(24): App\Models\Usuario->obtenerUsuario([...])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->login()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\proyectoFundamentos\\public\\index.php')
